# Generated by Django 5.0.7 on 2024-08-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdNumber', models.IntegerField()),
                ('NameRoom', models.CharField(max_length=30)),
            ],
        ),
    ]
