# Generated by Django 5.0.7 on 2024-08-08 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_rooms_idnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='NameRoom',
            new_name='name',
        ),
    ]
