# Generated by Django 5.0.7 on 2024-11-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_nameroom_rooms_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
