# Generated by Django 4.2.11 on 2024-11-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.FloatField(max_length=50),
        ),
    ]
